name: cids_cgi
description: CGI Design System for Flutter
version: 3.1.6
homepage: http://www.webcgi.com.br

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  cloud_firestore: ^4.4.4
  device_info_plus: ^8.1.0
  dio: ^5.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  # flutter_html: ^2.2.1
  flutter_widget_from_html: ^0.10.1
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.21
  local_auth_ios: ^1.1.1
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^3.0.3
  scan: ^1.6.0
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: br.com.cgisoftware.cids_cgi
        pluginClass: CidsCgiPlugin
      ios:
        pluginClass: CidsCgiPlugin
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - assets/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
